### ISSUE TITLE
Game skips pressed keys

### ISSUE THREAD

**Issue by up-left** [youkaicountry/yknytt#121]
This bug is hard to reproduce, but it's obvious when playing game for a long time.

Here is the save for the scene where it's almost impossible (for me) to pass the robot without noticing the missed jumps. (I've played it on every platform)

Maybe this issue is related: https://github.com/godotengine/godot/issues/36396

[Fubaka - Juni Gets a Food 1.ini.zip](https://github.com/youkaicountry/yknytt/files/5813270/Fubaka.-.Juni.Gets.a.Food.1.ini.zip)

**Comment by youkaicountry** [comment]
I have experienced this quite often as well. It is either due to issues with Godot engine itself as listed in that issue, or possible problems with detecting when Juni is on the ground and can jump. I have a workaround in mind if it is the input problem in that issue. I will try to work on this soon.

**Comment by youkaicountry** [comment]
I refactored Juni's input, and things seem to be acting better, including your save file. Can you verify on your machines? 
If you are still having issues I have some more ideas.

**Comment by up-left** [comment]
Ok, I'll answer later!

**Comment by up-left** [comment]
Unfortunately, the problem is still there.

**Comment by youkaicountry** [comment]
Okay, thanks for testing! I think it may involve the sensitivity of the `Grounded` check. I will play around with that next.

**Comment by youkaicountry** [comment]
I think I see what is going on. Due to subtle differences in the generated tile collision shapes, juni can enter the "Falling" state for a frame or two while running across some tilesets. During these frames she would not be able to jump at all without the double jump ability, and with the double jump ability she would be executing the "second jump" as if in the air. The tileset in that level appears to cause this issue.
I am exploring solutions now.

**Comment by youkaicountry** [comment]
I made some more changes to Juni's physics, hopefully without breaking anything :)
Juni tends to stick to uneven surfaces better, and there is now more leeway on jumping when running off of a ledge (it feels more forgiving as it does in the original game, hopefully not too much so)

Please check if this is any better

**Comment by up-left** [comment]
This is much better! I tried it and the number of missed jumps decreased.
But I found a bug: I tried to add an extra forgiving frame (changing FALL_LEEWAY to 0.04f), and the behaviour became too forgiving.
I wrote this test which may help you:
```
    private int count;
    private int count2;
    private bool last_grounded;

    private void checkDebugInput()
    {
        var pos = Position - GDArea.Position;
        if (!Grounded && last_grounded) { count2 = 0; GD.Print($"- {Grounded} {pos/24} {pos%24} {OS.GetTicksMsec()}"); }
        last_grounded = Grounded;
        count2++;
        if (juniInput.JumpEdge) { GD.Print($"{++count} {count2} {Grounded} {pos/24} {pos%24} {OS.GetTicksMsec()}"); }
    ...
    }
```
count2 is the number of forgiven frames. Output:
```
- False (6,294271, 4,697266) (7,0625, 16,73438) 18240
4 7 False (7,028646, 5,048828) (0,6875, 1,171875) 18356
```
-- 7 is too large number for extra frames

Also, in my opinion, sometimes ActionPressed comes too late. I cannot test it, maybe it happens at the OS level. This was the reason I tried to add extra frames.

**Comment by youkaicountry** [comment]
I have just committed further fixes to the jump logic. Now there are 5 frames of leeway after leaving a ledge, before transitioning to the fall state. 
This feels reasonably close to the original to me, but feel free to mess with the `FALL_LEEWAY` constant further until it feels right to you, 
Other than that I may close this issue as resolved soon if you have no objections.

**Comment by up-left** [comment]
Works great! Do you plan to remove JuniInput? Were IsActionJustPressed really missing keys?
Also JuniInput breaks KS+ automation. If you are not going to delete this workaround, I can fix it.

**Comment by up-left** [comment]
I've fixed the automation, but I've found that NoJump is broken. Could you please fix it?

**Comment by youkaicountry** [comment]
Ah, okay I will look into NoJump

I do plan to keep JuniInput as it is for now, simply because it cleans Juni.cs up a little. I think it could be useful as an abstraction  layer later on.
I will test IsActionJustPressed more at some point to determine if the workaround need to stay.

**Comment by youkaicountry** [comment]
Okay I've fixed NoJump. Looks like I got overzealous pruning what I thought was old code. I've restored it, adapted it to the new jumping code, and commented it so I don't forget what it's there for again :)

**Comment by youkaicountry** [comment]
Closing as resolved.

**Comment by up-left** [comment]
It still happens, but I cannot provide a certain scene.
A couple of times it happened when Juni came off the wall with up+right pressed. She jumped, but didn't move right.
It's still possible to get Juni not moving with left/right keys pressed, and she moves after pressing the key again.
I think to write a debug message to catch this case to investigate if the game consider key pressed, or it is missed after it in the game logic.

**Comment by up-left** [comment]
Seems to be a Windows keyboard buffer issue. Sometimes IsActionPressed doesn't even came to the application, or disappears when three keys is pressed at once. Doesn't happen on Linux and Android. Maybe it's even my keyboard driver problem =)

**Comment by up-left** [comment]
I can't press more than three keys on Windows, but it's possible on Linux and in other Windows applications (in the original game, for example). Maybe there is a way to solve this problem?

**Comment by up-left** [comment]
Hmm. Pressing four keys is possible at start, but something breaks during playing...

**Comment by up-left** [comment]
Do you still have this issue on Windows? If not, it can be considered machine-dependent or internal Godot issue and be closed.

**Comment by youkaicountry** [comment]
Issue does not seem to persist on either Windows or Linux, the two OS's I have access to.
Closing as resolved.
